% Auto-generated by cameraCalibrator app on 21-Nov-2021
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Users\amitc\Downloads\p11.jpeg',...
    'C:\Users\amitc\Downloads\p12.jpeg',...
    'C:\Users\amitc\Downloads\p13.jpeg',...
    'C:\Users\amitc\Downloads\p14.jpeg',...
    'C:\Users\amitc\Downloads\p15.jpeg',...
    'C:\Users\amitc\Downloads\p16.jpeg',...
    'C:\Users\amitc\Downloads\p17.jpeg',...
    'C:\Users\amitc\Downloads\p18.jpeg',...
    'C:\Users\amitc\Downloads\p19.jpeg',...
    'C:\Users\amitc\Downloads\p110.jpeg',...
    'C:\Users\amitc\Downloads\p111.jpeg',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 22;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')

%[rotationMatrix,translationVector] = extrinsics(imagePoints,worldPoints,cameraParams)
