% Auto-generated by cameraCalibrator app on 21-Nov-2021
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Users\owner\PycharmProjects\IRS_course\Amit\Assignment2\2bfc1d46-3e0c-4981-a4a9-df590bd919c1.JPG',...
    'C:\Users\owner\PycharmProjects\IRS_course\Amit\Assignment2\3f847ac3-9624-4fac-8d31-1532e38609af.JPG',...
    'C:\Users\owner\PycharmProjects\IRS_course\Amit\Assignment2\05d3ee68-8621-493a-a5d2-0961a6baa912.JPG',...
    'C:\Users\owner\PycharmProjects\IRS_course\Amit\Assignment2\8a6c589b-b372-4484-8cb3-de3caacfc34e.JPG',...
    'C:\Users\owner\PycharmProjects\IRS_course\Amit\Assignment2\41f2e728-8c4c-47d4-9d9a-704cdc7a42eb.JPG',...
    'C:\Users\owner\PycharmProjects\IRS_course\Amit\Assignment2\55d7a6f9-6440-49aa-8abf-ef0e2a8664c0.JPG',...
    'C:\Users\owner\PycharmProjects\IRS_course\Amit\Assignment2\83c024bf-0854-4f89-b907-4000f5a0ccdb.JPG',...
    'C:\Users\owner\PycharmProjects\IRS_course\Amit\Assignment2\ab169d85-9134-47a1-9dc8-086224b5e271.JPG',...
    'C:\Users\owner\PycharmProjects\IRS_course\Amit\Assignment2\c46d97e0-7129-413e-9047-664c52ca4f8f.JPG',...
    'C:\Users\owner\PycharmProjects\IRS_course\Amit\Assignment2\f02f4be5-f579-475d-9a8b-c9743842d4a6.JPG',...
    'C:\Users\owner\PycharmProjects\IRS_course\Amit\Assignment2\f45b23e1-57dd-4a9f-b49e-cceced429815.JPG',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 22;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
